apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: frontend
  labels:
    app.kubernetes.io/name: netflix-frontend
data:
  REACT_APP_API_URL: /api
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: backend
  labels:
    app.kubernetes.io/name: netflix-backend
data:
  NODE_ENV: production
  PORT: "5000"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: backend
  labels:
    app.kubernetes.io/name: netflix-backend
type: Opaque
stringData:
  DB_URL: mongodb://admin:admin@mongodb:27017/netflix?authSource=admin
